version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    build:
      context: .
    depends_on:
      - mysql
    environment:
      - PORT=${PORT:-8080}
    volumes:
      - ./www:/var/www/html/
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./docs:/var/www/html/docs
    ports:
      - "${PORT:-8080}:8080"
  mysql:
    platform: linux/amd64
    container_name: mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hintwave
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "9906:3306"
    volumes:
      - "./db:/var/lib/mysql"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_ABSOLUTE_URI: http://localhost:${PORT:-8080}/phpmyadmin/
    depends_on:
      - mysql
  phpdoc:
    image: phpdoc/phpdoc:3
    volumes:
      - ./www:/data/src
      - ./docs:/data/docs
    command: run -d /data/src -t /data/docs